import { StyleSheet } from 'react-native';

const NEON = '#C9E265';
const BG = '#050505';
const CARD_BG = '#121212';
const GRAY = '#888';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BG,
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 40,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 40,
        marginTop: 10,
    },
    cancelText: {
        color: GRAY,
        fontSize: 16,
        fontFamily: 'Montserrat_500Medium',
    },
    headerTitle: {
        color: '#fff',
        fontSize: 18,
        fontFamily: 'Montserrat_700Bold',
    },
    timeContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'baseline',
        marginBottom: 40,
    },
    timeText: {
        fontSize: 80,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        letterSpacing: -2,
    },
    ampmText: {
        fontSize: 24,
        color: GRAY,
        marginLeft: 10,
        fontFamily: 'Montserrat_600SemiBold',
    },
    sectionLabel: {
        color: GRAY,
        fontSize: 12,
        fontFamily: 'Montserrat_700Bold',
        marginBottom: 16,
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    modeToggleContainer: {
        flexDirection: 'row',
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 4,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    modeButton: {
        flex: 1,
        paddingVertical: 12,
        alignItems: 'center',
        borderRadius: 12,
    },
    modeButtonActive: {
        backgroundColor: '#1A1A1A',
        borderWidth: 1,
        borderColor: '#333',
    },
    modeButtonText: {
        color: GRAY,
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 14,
    },
    modeButtonTextActive: {
        color: '#fff',
        fontFamily: 'Montserrat_700Bold',
    },
    buddyCard: {
        borderWidth: 1,
        borderColor: '#1A1A1A',
        borderRadius: 20,
        padding: 20,
        marginBottom: 32,
        backgroundColor: CARD_BG,
    },
    buddyRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    buddyIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#1A1A1A',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
        borderWidth: 1,
        borderColor: '#333',
    },
    buddyInfo: {
        flex: 1,
    },
    buddyTitle: {
        color: '#fff',
        fontFamily: 'Montserrat_700Bold',
        fontSize: 16,
        marginBottom: 2,
    },
    buddySubtitle: {
        color: GRAY,
        fontSize: 13,
        fontFamily: 'Montserrat_500Medium',
    },
    changeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: 'rgba(201, 226, 101, 0.1)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(201, 226, 101, 0.2)',
    },
    changeButtonText: {
        color: NEON,
        fontFamily: 'Montserrat_600SemiBold',
        fontSize: 12,
    },
    usernameInput: {
        backgroundColor: '#050505',
        color: '#fff',
        padding: 14,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#333',
        fontFamily: 'Montserrat_500Medium',
        fontSize: 14,
    },
    buddyFooter: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 8,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#1A1A1A',
    },
    buddyFooterText: {
        color: '#666',
        fontSize: 12,
        flex: 1,
        lineHeight: 18,
        fontFamily: 'Montserrat_400Regular',
    },
    configItem: {
        marginBottom: 24,
    },
    configLabel: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Montserrat_600SemiBold',
        marginBottom: 12,
    },
    daysContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: CARD_BG,
        padding: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    dayButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#1A1A1A',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#333',
    },
    dayButtonActive: {
        backgroundColor: NEON,
        borderColor: NEON,
    },
    dayText: {
        color: GRAY,
        fontFamily: 'Montserrat_700Bold',
        fontSize: 12,
    },
    dayTextActive: {
        color: '#000',
    },
    configRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
        paddingVertical: 4,
    },
    configValueContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    configValue: {
        color: NEON,
        fontSize: 16,
        fontFamily: 'Montserrat_600SemiBold',
    },
    saveButton: {
        backgroundColor: NEON,
        borderRadius: 20,
        paddingVertical: 18,
        alignItems: 'center',
        marginTop: 20,
        shadowColor: NEON,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    saveButtonText: {
        color: '#000',
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        letterSpacing: 0.5,
    },
    // Wake Method Button
    wakeMethodButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1A1A1A',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 14,
        gap: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    wakeMethodText: {
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
        color: '#fff',
    },
    // Label Modal Styles
    labelModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.9)',
        justifyContent: 'flex-end',
    },
    labelModalContent: {
        backgroundColor: CARD_BG,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingBottom: 40,
        borderTopWidth: 1,
        borderTopColor: '#333',
    },
    labelModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    labelModalTitle: {
        fontSize: 20,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
    },
    defaultLabelsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginBottom: 24,
    },
    defaultLabelChip: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 16,
        backgroundColor: '#1A1A1A',
        borderWidth: 1,
        borderColor: '#333',
    },
    defaultLabelChipActive: {
        backgroundColor: 'rgba(201, 226, 101, 0.1)',
        borderColor: NEON,
    },
    defaultLabelText: {
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
        color: GRAY,
    },
    defaultLabelTextActive: {
        color: NEON,
    },
    customLabelContainer: {
        borderTopWidth: 1,
        borderTopColor: '#222',
        paddingTop: 24,
    },
    customLabelTitle: {
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
        color: GRAY,
        marginBottom: 16,
    },
    customLabelInputRow: {
        flexDirection: 'row',
        gap: 12,
    },
    customLabelInput: {
        flex: 1,
        backgroundColor: '#050505',
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 14,
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_500Medium',
        borderWidth: 1,
        borderColor: '#333',
    },
    customLabelSaveBtn: {
        backgroundColor: NEON,
        borderRadius: 14,
        paddingHorizontal: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    customLabelSaveBtnDisabled: {
        backgroundColor: '#333',
    },
    customLabelSaveBtnText: {
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
        color: '#000',
    },
});

export default styles;
