import { StyleSheet } from 'react-native';

const exploreStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 100,
    },
    header: {
        marginBottom: 25,
    },
    headerTitle: {
        fontSize: 32,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 5,
    },
    headerSubtitle: {
        fontSize: 16,
        color: '#888',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 14,
        marginBottom: 25,
        borderWidth: 1,
        borderColor: '#333',
    },
    searchIcon: {
        marginRight: 12,
    },
    searchInput: {
        flex: 1,
        color: '#fff',
        fontSize: 16,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 25,
    },
    statCard: {
        flex: 1,
        backgroundColor: '#111',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 5,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#222',
    },
    statNumber: {
        fontSize: 28,
        fontFamily: 'Montserrat_700Bold',
        color: '#C9E265',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 12,
        color: '#888',
        textAlign: 'center',
    },
    sectionTitle: {
        fontSize: 20,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 16,
    },
    userCard: {
        backgroundColor: '#111',
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#222',
    },
    userCardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    userImageContainer: {
        marginRight: 16,
        position: 'relative',
    },
    onlineIndicator: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: '#4CAF50',
        borderWidth: 2,
        borderColor: '#111',
    },
    userInfo: {
        flex: 1,
    },
    userName: {
        fontSize: 18,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 2,
    },
    userUsername: {
        fontSize: 14,
        color: '#C9E265',
        marginBottom: 4,
    },
    userBio: {
        fontSize: 14,
        color: '#888',
        lineHeight: 20,
    },
    userCardBottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#222',
    },
    streakContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    streakBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#2a2a1a',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        gap: 4,
    },
    streakText: {
        color: '#C9E265',
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
    },
    maxStreakBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a2a',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 12,
        gap: 4,
    },
    maxStreakText: {
        color: '#6B8AFF',
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
    },
    actionButtons: {
        flexDirection: 'row',
        gap: 10,
    },
    inviteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#C9E265',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 12,
        gap: 6,
    },
    inviteButtonText: {
        color: '#000',
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
    },
    profileButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#222',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 12,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 50,
    },
    loadingText: {
        color: '#888',
        marginTop: 12,
        fontSize: 16,
    },
    emptyContainer: {
        alignItems: 'center',
        paddingVertical: 50,
    },
    emptyIcon: {
        marginBottom: 16,
    },
    emptyText: {
        color: '#888',
        fontSize: 18,
        fontFamily: 'Montserrat_600SemiBold',
        marginBottom: 8,
    },
    emptySubtext: {
        color: '#666',
        fontSize: 14,
        textAlign: 'center',
    },
    featuredSection: {
        marginBottom: 25,
    },
    featuredScroll: {
        marginLeft: -20,
        paddingLeft: 20,
    },
    featuredCard: {
        width: 160,
        backgroundColor: '#111',
        borderRadius: 20,
        padding: 16,
        marginRight: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#222',
        position: 'relative',
    },
    featuredCardMe: {
        backgroundColor: '#1a2a1a',
        borderWidth: 2,
        borderColor: '#C9E265',
        shadowColor: '#C9E265',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 8,
    },
    youBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: '#C9E265',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
        zIndex: 10,
    },
    youBadgeText: {
        color: '#000',
        fontSize: 10,
        fontFamily: 'Montserrat_700Bold',
    },
    meRing: {
        position: 'absolute',
        top: -4,
        left: -4,
        right: -4,
        bottom: -4,
        borderRadius: 42,
        borderWidth: 3,
        borderColor: '#C9E265',
    },
    featuredImageContainer: {
        marginBottom: 12,
        position: 'relative',
    },
    featuredBadge: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: '#C9E265',
        borderRadius: 10,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    featuredBadgeMe: {
        backgroundColor: '#fff',
    },
    featuredName: {
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 4,
        textAlign: 'center',
    },
    featuredNameMe: {
        color: '#C9E265',
    },
    featuredStreak: {
        fontSize: 14,
        color: '#C9E265',
        fontFamily: 'Montserrat_600SemiBold',
    },
    featuredStreakMe: {
        color: '#fff',
    },
});

export default exploreStyles;
