import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const NEON = '#C9E265';
const BG = '#050505';
const CARD_BG = '#121212';
const GRAY = '#888';

const exploreStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BG,
    },
    scrollContent: {
        padding: 16,
        paddingBottom: 100,
    },
    header: {
        marginBottom: 20,
        marginTop: 10,
    },
    headerTitle: {
        fontSize: 32,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 4,
        letterSpacing: -0.5,
    },
    headerSubtitle: {
        fontSize: 14,
        color: GRAY,
        fontFamily: 'Montserrat_500Medium',
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: CARD_BG,
        borderRadius: 25,
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#222',
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_500Medium',
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
        gap: 10,
    },
    statCard: {
        flex: 1,
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 14,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    statNumber: {
        fontSize: 20,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 10,
        color: GRAY,
        textAlign: 'center',
        fontFamily: 'Montserrat_600SemiBold',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    sectionTitle: {
        fontSize: 18,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 16,
        marginTop: 8,
    },
    userCard: {
        backgroundColor: CARD_BG,
        borderRadius: 18,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    userCardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    userImageContainer: {
        marginRight: 14,
        position: 'relative',
    },
    onlineIndicator: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: NEON,
        borderWidth: 2,
        borderColor: CARD_BG,
    },
    userInfo: {
        flex: 1,
    },
    userName: {
        fontSize: 15,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 2,
    },
    userUsername: {
        fontSize: 12,
        color: NEON,
        marginBottom: 4,
        fontFamily: 'Montserrat_500Medium',
    },
    userBio: {
        fontSize: 12,
        color: '#999',
        lineHeight: 16,
        fontFamily: 'Montserrat_400Regular',
    },
    userCardBottom: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#222',
    },
    streakContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    streakBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 107, 53, 0.1)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        gap: 4,
    },
    streakText: {
        color: '#FF6B35',
        fontSize: 12,
        fontFamily: 'Montserrat_700Bold',
    },
    maxStreakBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(255, 215, 0, 0.1)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        gap: 4,
    },
    maxStreakText: {
        color: '#FFD700',
        fontSize: 12,
        fontFamily: 'Montserrat_700Bold',
    },
    actionButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    inviteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1A1A1A',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        gap: 6,
        borderWidth: 1,
        borderColor: '#333',
    },
    inviteButtonText: {
        color: '#fff',
        fontSize: 12,
        fontFamily: 'Montserrat_600SemiBold',
    },
    profileButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1A1A1A',
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#333',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 50,
        backgroundColor: BG,
    },
    loadingText: {
        color: GRAY,
        marginTop: 16,
        fontSize: 14,
        fontFamily: 'Montserrat_500Medium',
    },
    emptyContainer: {
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyIcon: {
        marginBottom: 16,
        opacity: 0.5,
    },
    emptyText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Montserrat_600SemiBold',
        marginBottom: 8,
    },
    emptySubtext: {
        color: GRAY,
        fontSize: 14,
        textAlign: 'center',
        fontFamily: 'Montserrat_400Regular',
    },
    featuredSection: {
        marginBottom: 24,
    },
    featuredScroll: {
        paddingRight: 16,
    },
    featuredCard: {
        width: 120,
        backgroundColor: CARD_BG,
        borderRadius: 16,
        padding: 12,
        marginRight: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#1A1A1A',
        position: 'relative',
    },
    featuredCardMe: {
        backgroundColor: 'rgba(201, 226, 101, 0.05)',
        borderColor: 'rgba(201, 226, 101, 0.3)',
    },
    youBadge: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: NEON,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
        zIndex: 10,
    },
    youBadgeText: {
        color: '#000',
        fontSize: 8,
        fontFamily: 'Montserrat_700Bold',
    },
    meRing: {
        position: 'absolute',
        top: -3,
        left: -3,
        right: -3,
        bottom: -3,
        borderRadius: 40,
        borderWidth: 2,
        borderColor: NEON,
    },
    featuredImageContainer: {
        marginBottom: 10,
        position: 'relative',
        marginTop: 4,
    },
    featuredBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: '#FF6B35',
        borderRadius: 10,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: CARD_BG,
    },
    featuredBadgeMe: {
        borderColor: '#1a2a1a',
    },
    featuredName: {
        fontSize: 13,
        fontFamily: 'Montserrat_600SemiBold',
        color: '#fff',
        marginBottom: 4,
        textAlign: 'center',
    },
    featuredNameMe: {
        color: NEON,
    },
    featuredStreak: {
        fontSize: 11,
        color: GRAY,
        fontFamily: 'Montserrat_500Medium',
    },
    featuredStreakMe: {
        color: '#fff',
    },
});

export default exploreStyles;
