import { StyleSheet } from 'react-native';

const homeStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollContent: {
        padding: 14,
        paddingBottom: 30,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    logoContainer: {
        width: 28,
        height: 28,
        backgroundColor: '#C9E265',
        borderRadius: 7,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    notificationButton: {
        position: 'relative',
    },
    badge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: 'red',
        borderRadius: 8,
        width: 14,
        height: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: '#fff',
        fontSize: 9,
        fontFamily: 'Montserrat_700Bold',
    },
    profileImageContainer: {
        width: 28,
        height: 28,
        borderRadius: 14,
        overflow: 'hidden',
        backgroundColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileImage: {
        width: '100%',
        height: '100%',
        borderRadius: 14,
    },
    profilePlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: '#C9E265',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileInitials: {
        color: '#000',
        fontSize: 12,
        fontFamily: 'Montserrat_700Bold',
    },
    streakCard: {
        backgroundColor: '#111',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#333',
        marginBottom: 20,
    },
    streakHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    streakLabel: {
        color: '#888',
        fontSize: 13,
    },
    shareBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#2a2a1a',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#C9E265',
    },
    shareBadgeText: {
        color: '#C9E265',
        fontSize: 11,
        fontFamily: 'Montserrat_600SemiBold',
    },
    streakCountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 4,
    },
    streakCount: {
        fontSize: 32,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
    },
    fireEmoji: {
        fontSize: 28,
    },
    streakSubtext: {
        color: '#888',
        fontSize: 13,
        marginBottom: 16,
    },
    streakProgress: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    progressSquare: {
        width: 22,
        height: 22,
        borderRadius: 3,
        backgroundColor: '#222',
    },
    progressSquareActive: {
        backgroundColor: '#C9E265',
    },
    progressSquareInactive: {
        backgroundColor: '#222',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 15,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
    },
    seeAllText: {
        color: '#C9E265',
        fontSize: 13,
    },
    alarmCard: {
        backgroundColor: '#000',
        borderRadius: 16,
        padding: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#222',
    },
    alarmHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    alarmDate: {
        color: '#888',
        fontSize: 13,
    },
    alarmActions: {
        flexDirection: 'row',
        gap: 8,
    },
    actionButton: {
        padding: 5,
        backgroundColor: '#1a1a1a',
        borderRadius: 8,
    },
    timeContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        marginBottom: 16,
    },
    timeText: {
        fontSize: 42,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
    },
    ampmText: {
        fontSize: 16,
        color: '#888',
        marginLeft: 8,
    },
    alarmFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    modeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    modeText: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_500Medium',
    },
    quickActionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
        marginTop: 12,
    },
    quickActionItem: {
        backgroundColor: '#111',
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        width: '30%',
        aspectRatio: 1,
        justifyContent: 'center',
    },
    quickActionIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#1a1a1a',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    quickActionText: {
        color: '#fff',
        fontSize: 13,
        fontFamily: 'Montserrat_500Medium',
    },
    socialCard: {
        backgroundColor: '#111',
        borderRadius: 16,
        padding: 12,
        marginBottom: 16,
    },
    socialContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    socialAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#C9E265',
        marginRight: 8,
    },
    socialTextContainer: {
        flex: 1,
    },
    socialTitle: {
        color: '#fff',
        fontSize: 13,
        fontFamily: 'Montserrat_700Bold',
        marginBottom: 2,
    },
    socialSubtitle: {
        color: '#888',
        fontSize: 11,
    },
    thumbsUpButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#1a1a1a',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#333',
    },
    achievementBadge: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#1a1a1a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    heatmapContainer: {
        marginTop: 16,
    },
    heatmapTitle: {
        color: '#888',
        fontSize: 11,
        marginBottom: 8,
        textAlign: 'center',
    },
    heatmap: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 3,
        marginBottom: 8,
    },
    heatmapDayContainer: {
        flex: 1,
    },
    heatmapBox: {
        aspectRatio: 1,
        borderRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#222',
    },
    heatmapCount: {
        color: '#fff',
        fontSize: 10,
        fontFamily: 'Montserrat_700Bold',
    },
    heatmapLegend: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 3,
        marginTop: 6,
    },
    legendText: {
        color: '#666',
        fontSize: 9,
    },
    legendBox: {
        width: 10,
        height: 10,
        borderRadius: 2,
    },
    // Banner Ad
    bannerAdContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        alignItems: 'center',
        backgroundColor: '#000',
        paddingVertical: 5,
    },
});

export default homeStyles;
