import { StyleSheet } from 'react-native';

const homeStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollContent: {
        padding: 20,
        paddingBottom: 40,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 30,
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    logoContainer: {
        width: 32,
        height: 32,
        backgroundColor: '#C9E265',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    notificationButton: {
        position: 'relative',
    },
    badge: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: 'red',
        borderRadius: 10,
        width: 16,
        height: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    profileImageContainer: {
        width: 32,
        height: 32,
        borderRadius: 16,
        overflow: 'hidden',
        backgroundColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileImage: {
        width: '100%',
        height: '100%',
        borderRadius: 16,
    },
    profilePlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: '#C9E265',
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileInitials: {
        color: '#000',
        fontSize: 14,
        fontWeight: 'bold',
    },
    streakCard: {
        backgroundColor: '#111',
        borderRadius: 20,
        padding: 20,
        borderWidth: 1,
        borderColor: '#333',
        marginBottom: 30,
    },
    streakHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    streakLabel: {
        color: '#888',
        fontSize: 14,
    },
    shareBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        backgroundColor: '#2a2a1a',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#C9E265',
    },
    shareBadgeText: {
        color: '#C9E265',
        fontSize: 12,
        fontWeight: '600',
    },
    streakCountContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 5,
    },
    streakCount: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#fff',
    },
    fireEmoji: {
        fontSize: 32,
    },
    streakSubtext: {
        color: '#888',
        fontSize: 14,
        marginBottom: 20,
    },
    streakProgress: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    progressSquare: {
        width: 25,
        height: 25,
        borderRadius: 4,
        backgroundColor: '#222',
    },
    progressSquareActive: {
        backgroundColor: '#C9E265',
    },
    progressSquareInactive: {
        backgroundColor: '#222',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    seeAllText: {
        color: '#C9E265',
        fontSize: 14,
    },
    alarmCard: {
        backgroundColor: '#000',
        borderRadius: 20,
        padding: 20,
        marginBottom: 30,
        borderWidth: 1,
        borderColor: '#222',
    },
    alarmHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    alarmDate: {
        color: '#888',
        fontSize: 14,
    },
    alarmActions: {
        flexDirection: 'row',
        gap: 10,
    },
    actionButton: {
        padding: 5,
        backgroundColor: '#1a1a1a',
        borderRadius: 8,
    },
    timeContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        marginBottom: 20,
    },
    timeText: {
        fontSize: 48,
        fontWeight: 'bold',
        color: '#fff',
    },
    ampmText: {
        fontSize: 20,
        color: '#888',
        marginLeft: 10,
    },
    alarmFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    modeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    modeText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '500',
    },
    quickActionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 30,
        marginTop: 15,
    },
    quickActionItem: {
        backgroundColor: '#111',
        borderRadius: 20,
        padding: 20,
        alignItems: 'center',
        width: '30%',
        aspectRatio: 1,
        justifyContent: 'center',
    },
    quickActionIcon: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#1a1a1a',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    quickActionText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    socialCard: {
        backgroundColor: '#111',
        borderRadius: 20,
        padding: 15,
        marginBottom: 20,
    },
    socialContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    socialAvatar: {
        width: 35,
        height: 35,
        borderRadius: 17.5,
        backgroundColor: '#C9E265',
        marginRight: 10,
    },
    socialTextContainer: {
        flex: 1,
    },
    socialTitle: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    socialSubtitle: {
        color: '#888',
        fontSize: 12,
    },
    thumbsUpButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#1a1a1a',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#333',
    },
    heatmapContainer: {
        marginTop: 20,
    },
    heatmapTitle: {
        color: '#888',
        fontSize: 12,
        marginBottom: 10,
        textAlign: 'center',
    },
    heatmap: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 4,
        marginBottom: 10,
    },
    heatmapDayContainer: {
        flex: 1,
    },
    heatmapBox: {
        aspectRatio: 1,
        borderRadius: 4,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#222',
    },
    heatmapCount: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    heatmapLegend: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 4,
        marginTop: 8,
    },
    legendText: {
        color: '#666',
        fontSize: 10,
    },
    legendBox: {
        width: 12,
        height: 12,
        borderRadius: 2,
    },
});

export default homeStyles;
