import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollContent: {
        padding: 16,
        paddingBottom: 32,
    },
    header: {
        marginBottom: 16,
    },
    backButton: {
        width: 36,
        height: 36,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    titleSection: {
        alignItems: 'center',
        marginBottom: 32,
    },
    iconContainer: {
        width: 85,
        height: 85,
        borderRadius: 42,
        backgroundColor: '#1a1a1a',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        borderWidth: 2,
        borderColor: '#C9E265',
    },
    title: {
        fontSize: 24,
        fontFamily: 'Montserrat_700Bold',
        color: '#C9E265',
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 15,
        color: '#888',
        textAlign: 'center',
        lineHeight: 22,
        paddingHorizontal: 16,
    },
    permissionsContainer: {
        gap: 16,
        marginBottom: 24,
    },
    permissionCard: {
        backgroundColor: '#111',
        borderRadius: 14,
        padding: 16,
        borderWidth: 1,
        borderColor: '#222',
    },
    cardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 12,
    },
    stepNumber: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#C9E265',
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepNumberText: {
        fontSize: 15,
        fontFamily: 'Montserrat_700Bold',
        color: '#000',
    },
    cardTitleContainer: {
        flex: 1,
    },
    cardTitle: {
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        color: '#fff',
        marginBottom: 4,
    },
    cardSubtitle: {
        fontSize: 13,
        color: '#888',
        lineHeight: 18,
    },
    actionButton: {
        backgroundColor: '#C9E265',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        gap: 6,
    },
    actionButtonText: {
        fontSize: 13,
        fontFamily: 'Montserrat_700Bold',
        color: '#000',
    },
    infoBox: {
        flexDirection: 'row',
        backgroundColor: '#1a1a1a',
        padding: 14,
        borderRadius: 10,
        gap: 10,
        alignItems: 'flex-start',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#333',
    },
    infoText: {
        flex: 1,
        fontSize: 14,
        color: '#aaa',
        lineHeight: 20,
    },
    continueButton: {
        backgroundColor: '#222',
        paddingVertical: 16,
        borderRadius: 30,
        alignItems: 'center',
        marginBottom: 20,
    },
    continueButtonActive: {
        backgroundColor: '#C9E265',
    },
    continueButtonText: {
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        color: '#666',
    },
    continueButtonTextActive: {
        color: '#000',
    },
    statusContainer: {
        alignItems: 'center',
    },
    statusText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        paddingHorizontal: 20,
    },
    manualSection: {
        backgroundColor: '#1a1a1a',
        borderRadius: 16,
        padding: 20,
        marginBottom: 30,
        borderWidth: 2,
        borderColor: '#C9E265',
    },
    manualHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 10,
    },
    manualHeaderText: {
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        color: '#C9E265',
    },
    manualDescription: {
        fontSize: 14,
        color: '#aaa',
        marginBottom: 20,
        lineHeight: 20,
    },
    manualCard: {
        backgroundColor: '#222',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#333',
    },
    manualCardHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
    },
    manualStepNumber: {
        backgroundColor: '#C9E265',
    },
    manualButton: {
        backgroundColor: '#C9E265',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        gap: 6,
        marginTop: 12,
    },
    manualButtonText: {
        flex: 1,
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
        color: '#000',
    },
    settingsButton: {
        backgroundColor: '#C9E265',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 12,
        gap: 8,
        marginTop: 8,
    },
    settingsButtonText: {
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        color: '#000',
    },
});

export default styles;
