import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const NEON = '#C9E265';
const BG = '#000';
const GRAY = '#BDBDBD';

const profileStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BG,
    },
    scroll: {
        padding: 12,
        paddingBottom: 30,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 22,
        fontFamily: 'Montserrat_700Bold',
    },
    iconButton: {
        padding: 4,
    },
    card: {
        backgroundColor: '#070707',
        borderRadius: 14,
        padding: 14,
        alignItems: 'center',
        marginBottom: 12,
        shadowColor: '#000',
        shadowOpacity: 0.5,
        shadowRadius: 8,
        elevation: 4,
    },
    avatarContainer: {
        position: 'relative',
        marginBottom: 10,
    },
    avatarRing: {
        width: 90,
        height: 90,
        borderRadius: 45,
        borderWidth: 3,
        borderColor: NEON,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 2,
    },
    avatar: {
        width: 82,
        height: 82,
        borderRadius: 41,
        overflow: 'hidden',
    },
    badge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: NEON,
        width: 26,
        height: 26,
        borderRadius: 13,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 3,
        borderColor: '#070707',
    },
    name: {
        color: '#fff',
        fontSize: 18,
        fontFamily: 'Montserrat_700Bold',
    },
    username: {
        color: GRAY,
        fontSize: 13,
        marginTop: 3,
    },
    bio: {
        color: '#9f9f9f',
        fontSize: 12,
        marginTop: 6,
        textAlign: 'center',
    },
    shareButton: {
        marginTop: 10,
        backgroundColor: NEON,
        paddingVertical: 8,
        paddingHorizontal: 18,
        borderRadius: 999,
        flexDirection: 'row',
        alignItems: 'center',
    },
    shareText: {
        color: '#000',
        fontFamily: 'Montserrat_700Bold',
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginVertical: 10,
    },
    statBox: {
        flex: 1,
        marginHorizontal: 4,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: NEON,
        paddingVertical: 10,
        alignItems: 'center',
        backgroundColor: '#050505',
    },
    statNumber: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_700Bold',
    },
    statLabel: {
        color: GRAY,
        fontSize: 12,
        marginTop: 3,
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 16,
        marginBottom: 10,
    },
    sectionTitle: {
        color: '#fff',
        fontFamily: 'Montserrat_700Bold',
        fontSize: 15,
    },
    viewAllText: {
        color: NEON,
        fontSize: 12,
        fontFamily: 'Montserrat_600SemiBold',
    },
    historySubHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    monthText: {
        color: GRAY,
        fontSize: 12,
    },
    legend: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
    },
    legendText: {
        color: GRAY,
        fontSize: 10,
    },
    legendSquare1: {
        width: 12,
        height: 12,
        borderRadius: 2,
        backgroundColor: '#1a2a1a',
    },
    legendSquare2: {
        width: 12,
        height: 12,
        borderRadius: 2,
        backgroundColor: '#2d4a2d',
    },
    legendSquare3: {
        width: 12,
        height: 12,
        borderRadius: 2,
        backgroundColor: '#6a9a3d',
    },
    legendSquare4: {
        width: 12,
        height: 12,
        borderRadius: 2,
        backgroundColor: NEON,
    },
    achCount: {
        color: GRAY,
        fontSize: 12,
    },
    gridContainer: {
        marginTop: 8,
        width: '100%',
        flexDirection: 'column',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        gap: 2.5,
        paddingHorizontal: 2,
        height: (7 * 20) + (6 * 2.5), // 7 rows * height + gaps
    },
    gridSquare: {
        width: (width - 24) / 13 - 2.5, // 13 columns to fit 90 days (90/7 ≈ 13 weeks)
        height: 20,
        borderRadius: 3,
        backgroundColor: '#1a1a1a',
    },
    gridSquareLight: {
        backgroundColor: '#1a2a1a',
    },
    gridSquareMedium: {
        backgroundColor: '#2d4a2d',
    },
    gridSquareHigh: {
        backgroundColor: '#6a9a3d',
    },
    gridSquareFilled: {
        backgroundColor: NEON,
    },
    achRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 14,
        marginBottom: 20,
    },
    achItem: {
        alignItems: 'center',
        width: (width - 24) / 4,
    },
    achCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#0b0b0b',
        justifyContent: 'center',
        alignItems: 'center',
    },
    achCircleArrow: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: 'rgba(201, 226, 101, 0.15)',
        borderWidth: 1,
        borderColor: NEON,
        borderStyle: 'dashed',
        justifyContent: 'center',
        alignItems: 'center',
    },
    achievedRing: {
        borderWidth: 2,
        borderColor: NEON,
    },
    achLabel: {
        color: GRAY,
        fontSize: 10,
        marginTop: 6,
        textAlign: 'center',
    },
    achLabelMore: {
        color: NEON,
        fontSize: 10,
        marginTop: 6,
        textAlign: 'center',
    },
    settingsHeader: {
        color: '#fff',
        fontFamily: 'Montserrat_700Bold',
        fontSize: 15,
        marginTop: 8,
        marginBottom: 10,
    },
    settingsCard: {
        borderRadius: 10,
        backgroundColor: '#070707',
        overflow: 'hidden',
    },
    settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderBottomColor: '#121212',
        borderBottomWidth: 1,
    },
    settingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    settingLabel: {
        color: '#fff',
        marginLeft: 12,
    },
    premiumRow: {
        marginTop: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 10,
        backgroundColor: '#070707',
    },
    premiumText: {
        color: '#fff',
        marginLeft: 10,
    },
    logoutButton: {
        marginTop: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 10,
        backgroundColor: NEON,
    },
    logoutText: {
        color: '#000',
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
    },
    versionText: {
        color: GRAY,
        fontSize: 12,
        textAlign: 'center',
        marginTop: 16,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.8)',
    },
    modalContent: {
        backgroundColor: '#111',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        height: '80%',
        borderTopWidth: 1,
        borderColor: '#333',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontFamily: 'Montserrat_700Bold',
    },
    modalForm: {
        flex: 1,
    },
    inputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        color: '#888',
        fontSize: 14,
        marginBottom: 8,
        fontFamily: 'Montserrat_600SemiBold',
    },
    input: {
        backgroundColor: '#222',
        borderRadius: 12,
        padding: 16,
        color: '#fff',
        fontSize: 16,
        borderWidth: 1,
        borderColor: '#333',
    },
    textArea: {
        height: 100,
        textAlignVertical: 'top',
    },
    saveButton: {
        backgroundColor: NEON,
        borderRadius: 30,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 40,
    },
    saveButtonText: {
        color: '#000',
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
    },
    // Friends Button Styles
    friendsButton: {
        backgroundColor: NEON,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        marginVertical: 10,
    },
    friendsButtonText: {
        color: '#000',
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
    },
    friendsCountBadge: {
        backgroundColor: '#000',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 3,
        marginLeft: 10,
    },
    friendsCountText: {
        color: NEON,
        fontSize: 13,
        fontFamily: 'Montserrat_700Bold',
    },
    // Friends Modal Styles
    friendsModalContent: {
        backgroundColor: '#111',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        height: '75%',
        borderTopWidth: 1,
        borderColor: '#333',
    },
    friendsList: {
        paddingBottom: 20,
    },
    friendCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        borderRadius: 10,
        padding: 12,
        marginBottom: 8,
    },
    friendInfo: {
        flex: 1,
        marginLeft: 12,
    },
    friendName: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_600SemiBold',
    },
    friendBio: {
        color: GRAY,
        fontSize: 12,
        marginTop: 2,
    },
    emptyFriendsContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 30,
    },
    emptyFriendsText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Montserrat_600SemiBold',
        marginTop: 16,
    },
    emptyFriendsSubtext: {
        color: GRAY,
        fontSize: 14,
        textAlign: 'center',
        marginTop: 8,
    },
    exploreFriendsButton: {
        backgroundColor: NEON,
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 30,
        marginTop: 24,
    },
    exploreFriendsText: {
        color: '#000',
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
    },
    actionButtons: {
        marginTop: 24,
        gap: 12,
    },
    primaryBtn: {
        backgroundColor: NEON,
        padding: 14,
        borderRadius: 12,
        alignItems: 'center',
    },
    primaryBtnText: {
        color: '#000',
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
    },
    secondaryBtn: {
        backgroundColor: '#222',
        padding: 14,
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#333',
    },
    secondaryBtnText: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Montserrat_600SemiBold',
    },
    // Avatar Picker Modal Styles
    avatarPickerContent: {
        backgroundColor: '#111',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        paddingBottom: 40,
        borderTopWidth: 1,
        borderColor: '#333',
    },
    avatarPickerSubtitle: {
        color: GRAY,
        fontSize: 14,
        textAlign: 'center',
        marginBottom: 24,
    },
    avatarOptionsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 16,
        marginBottom: 24,
    },
    avatarOption: {
        alignItems: 'center',
    },
    avatarOptionRing: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 3,
        borderColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
    },
    avatarOptionSelected: {
        borderColor: NEON,
    },
    refreshAvatarsButton: {
        backgroundColor: NEON,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 30,
        marginTop: 8,
    },
    refreshAvatarsText: {
        color: '#000',
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
    },
    savingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    savingText: {
        color: '#fff',
        fontSize: 14,
        marginTop: 12,
    },

    // Achievements Modal Styles
    achievementsModalContent: {
        backgroundColor: '#111',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        height: '85%',
        borderTopWidth: 1,
        borderColor: '#333',
    },
    achModalSubtitle: {
        color: GRAY,
        fontSize: 12,
        marginTop: 4,
    },
    achievementsList: {
        flex: 1,
        marginTop: 10,
    },
    achievementModalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1a1a1a',
        borderRadius: 12,
        padding: 14,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#2a2a2a',
    },
    achievementModalItemLocked: {
        opacity: 0.6,
        backgroundColor: '#0d0d0d',
        borderColor: '#1a1a1a',
    },
    achModalCircle: {
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#222',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 14,
    },
    achModalCircleEarned: {
        backgroundColor: 'rgba(201, 226, 101, 0.15)',
        borderWidth: 2,
        borderColor: NEON,
    },
    achModalInfo: {
        flex: 1,
        marginRight: 10,
    },
    achModalName: {
        color: '#fff',
        fontSize: 14,
        fontFamily: 'Montserrat_700Bold',
    },
    achModalNameLocked: {
        color: '#888',
    },
    achModalDesc: {
        color: GRAY,
        fontSize: 11,
        marginTop: 3,
    },
    achModalDescLocked: {
        color: '#555',
    },
    achModalDate: {
        color: NEON,
        fontSize: 10,
        marginTop: 4,
    },
    emptyAchievements: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyAchievementsText: {
        color: GRAY,
        fontSize: 14,
        marginTop: 16,
    },
});

export default profileStyles;
