import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const NEON = '#C9E265';
const BG = '#050505';
const CARD_BG = '#121212';
const GRAY = '#888';

const profileStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: BG,
    },
    scroll: {
        paddingVertical: 20,
        paddingHorizontal: 10,
        paddingBottom: 40,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 24,
        marginTop: 10,
    },
    headerTitle: {
        color: '#fff',
        fontSize: 24,
        fontFamily: 'Montserrat_700Bold',
        letterSpacing: 0.5,
    },
    iconButton: {
        padding: 8,
        backgroundColor: CARD_BG,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#1A1A1A',
        marginLeft: 8,
    },
    card: {
        backgroundColor: CARD_BG,
        borderRadius: 24,
        paddingVertical: 10,
        paddingHorizontal: 0,
        alignItems: 'center',
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    avatarContainer: {
        position: 'relative',
        marginBottom: 16,
    },
    avatarRing: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: NEON,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 4,
        backgroundColor: 'rgba(201, 226, 101, 0.05)',
    },
    avatar: {
        width: 88,
        height: 88,
        borderRadius: 44,
        overflow: 'hidden',
    },
    badge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: NEON,
        width: 32,
        height: 32,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 4,
        borderColor: CARD_BG,
    },
    name: {
        color: '#fff',
        fontSize: 20,
        fontFamily: 'Montserrat_700Bold',
        marginBottom: 4,
    },
    username: {
        color: NEON,
        fontSize: 14,
        fontFamily: 'Montserrat_600SemiBold',
        marginBottom: 12,
    },
    bio: {
        color: GRAY,
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        fontFamily: 'Montserrat_500Medium',
        paddingHorizontal: 20,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
        gap: 12,
    },
    statBox: {
        flex: 1,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#1A1A1A',
        paddingVertical: 16,
        alignItems: 'center',
        backgroundColor: CARD_BG,
    },
    statNumber: {
        color: '#fff',
        fontSize: 20,
        fontFamily: 'Montserrat_700Bold',
        marginBottom: 4,
    },
    statLabel: {
        color: GRAY,
        fontSize: 12,
        fontFamily: 'Montserrat_600SemiBold',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    // Weekly Bar Chart Styles
    weeklyChartContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 20,
        paddingTop: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    barColumn: {
        alignItems: 'center',
        flex: 1,
    },
    barCount: {
        color: NEON,
        fontSize: 12,
        fontFamily: 'Montserrat_700Bold',
        height: 18,
        marginBottom: 6,
    },
    barTrack: {
        width: 32,
        height: 100,
        backgroundColor: '#050505',
        borderRadius: 8,
        justifyContent: 'flex-end',
        alignItems: 'center',
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    bar: {
        width: '100%',
        backgroundColor: '#1A1A1A',
        borderRadius: 8,
    },
    barFilled: {
        backgroundColor: 'rgba(201, 226, 101, 0.3)',
    },
    barToday: {
        backgroundColor: NEON,
    },
    barDay: {
        color: GRAY,
        fontSize: 11,
        marginTop: 8,
        fontFamily: 'Montserrat_600SemiBold',
    },
    barDayToday: {
        color: NEON,
        fontFamily: 'Montserrat_700Bold',
    },
    sectionHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 16,
    },
    sectionTitle: {
        color: '#fff',
        fontFamily: 'Montserrat_700Bold',
        fontSize: 18,
    },
    viewAllText: {
        color: NEON,
        fontSize: 13,
        fontFamily: 'Montserrat_600SemiBold',
    },
    historySubHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    monthText: {
        color: GRAY,
        fontSize: 13,
        fontFamily: 'Montserrat_600SemiBold',
    },
    legend: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    legendText: {
        color: GRAY,
        fontSize: 11,
        fontFamily: 'Montserrat_500Medium',
    },
    legendSquare: {
        width: 14,
        height: 14,
        borderRadius: 3,
    },
    achCount: {
        color: GRAY,
        fontSize: 13,
        fontFamily: 'Montserrat_600SemiBold',
    },
    gridContainer: {
        marginTop: 0,
        width: '100%',
        flexDirection: 'column',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        gap: 3,
        paddingHorizontal: 0,
        height: (7 * 22) + (6 * 3), // Adjusted for larger squares and gaps
        marginBottom: 24,
    },
    gridSquare: {
        width: (width - 40 - (12 * 3)) / 13, // Adjusted calculation
        height: 22,
        borderRadius: 4,
        backgroundColor: '#1A1A1A',
    },
    gridSquareLight: {
        backgroundColor: '#1a2a1a',
    },
    gridSquareMedium: {
        backgroundColor: '#2d4a2d',
    },
    gridSquareHigh: {
        backgroundColor: '#6a9a3d',
    },
    gridSquareFilled: {
        backgroundColor: NEON,
    },
    // Full Width Stacked Bar Charts
    fullWidthChartCard: {
        backgroundColor: CARD_BG,
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    chartCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    chartCardTitle: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
    },
    chartCardTotal: {
        color: NEON,
        fontSize: 13,
        fontFamily: 'Montserrat_600SemiBold',
    },
    fullBarContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        height: 120,
    },
    fullBarColumn: {
        alignItems: 'center',
        flex: 1,
    },
    barValueLabel: {
        color: NEON,
        fontSize: 11,
        fontFamily: 'Montserrat_700Bold',
        height: 16,
        marginBottom: 6,
    },
    fullBarTrack: {
        width: 36,
        height: 80,
        backgroundColor: '#050505',
        borderRadius: 8,
        justifyContent: 'flex-end',
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    fullBar: {
        width: '100%',
        backgroundColor: '#1A1A1A',
        borderRadius: 8,
    },
    fullBarFilled: {
        backgroundColor: 'rgba(201, 226, 101, 0.3)',
    },
    fullBarToday: {
        backgroundColor: NEON,
    },
    fullBarDay: {
        color: GRAY,
        fontSize: 11,
        marginTop: 8,
        fontFamily: 'Montserrat_500Medium',
    },
    fullBarDayToday: {
        color: NEON,
        fontFamily: 'Montserrat_700Bold',
    },
    achRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
        marginBottom: 32,
    },
    achItem: {
        alignItems: 'center',
        width: (width - 40) / 4,
    },
    achCircle: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: CARD_BG,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#1A1A1A',
        marginBottom: 8,
    },
    achCircleArrow: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(201, 226, 101, 0.1)',
        borderWidth: 1,
        borderColor: NEON,
        borderStyle: 'dashed',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    achievedRing: {
        borderWidth: 2,
        borderColor: NEON,
        backgroundColor: 'rgba(201, 226, 101, 0.05)',
    },
    achLabel: {
        color: GRAY,
        fontSize: 11,
        textAlign: 'center',
        fontFamily: 'Montserrat_500Medium',
        lineHeight: 14,
    },
    achLabelMore: {
        color: NEON,
        fontSize: 11,
        textAlign: 'center',
        fontFamily: 'Montserrat_600SemiBold',
    },
    settingsHeader: {
        color: '#fff',
        fontFamily: 'Montserrat_700Bold',
        fontSize: 18,
        marginTop: 8,
        marginBottom: 16,
    },
    settingsCard: {
        borderRadius: 20,
        backgroundColor: CARD_BG,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#1A1A1A',
        marginBottom: 16,
    },
    settingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderBottomColor: '#1A1A1A',
        borderBottomWidth: 1,
    },
    settingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    settingLabel: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_500Medium',
    },
    premiumRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 20,
        backgroundColor: CARD_BG,
        borderWidth: 1,
        borderColor: 'rgba(201, 226, 101, 0.3)',
        marginBottom: 16,
    },
    premiumText: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_600SemiBold',
    },
    logoutButton: {
        marginTop: 8,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 20,
        backgroundColor: '#1A1A1A',
        borderWidth: 1,
        borderColor: '#333',
    },
    logoutText: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_700Bold',
    },
    versionText: {
        color: '#444',
        fontSize: 12,
        textAlign: 'center',
        marginTop: 24,
        fontFamily: 'Montserrat_500Medium',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0,0,0,0.9)',
    },
    modalContent: {
        backgroundColor: CARD_BG,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        height: '70%',
        borderTopWidth: 1,
        borderColor: '#333',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 20,
        fontFamily: 'Montserrat_700Bold',
    },
    modalForm: {
        flexGrow: 1,
        marginBottom: "auto"
    },
    inputGroup: {
        marginBottom: 24,
    },
    inputLabel: {
        color: GRAY,
        fontSize: 14,
        marginBottom: 10,
        fontFamily: 'Montserrat_600SemiBold',
    },
    input: {
        backgroundColor: '#050505',
        borderRadius: 14,
        padding: 16,
        color: '#fff',
        fontSize: 16,
        borderWidth: 1,
        borderColor: '#333',
        fontFamily: 'Montserrat_500Medium',
    },
    textArea: {
        height: 120,
        textAlignVertical: 'top',
    },
    saveButton: {
        backgroundColor: NEON,
        borderRadius: 20,
        paddingVertical: 18,
        alignItems: 'center',
        marginTop: 'auto',
        marginBottom: 20,
    },
    saveButtonText: {
        color: '#000',
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
    },
    // Friends Button Styles
    friendsButton: {
        backgroundColor: CARD_BG,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 20,
        borderRadius: 16,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    friendsButtonText: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_600SemiBold',
    },
    friendsCountBadge: {
        backgroundColor: NEON,
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 4,
        marginLeft: 12,
    },
    friendsCountText: {
        color: '#000',
        fontSize: 12,
        fontFamily: 'Montserrat_700Bold',
    },
    // Friends Modal Styles
    friendsModalContent: {
        backgroundColor: CARD_BG,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 10,
        height: '80%',
        borderTopWidth: 1,
        borderColor: '#333',
    },
    friendsList: {
        paddingBottom: 20,
    },
    friendCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#050505',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    friendInfo: {
        flex: 1,
        marginLeft: 16,
    },
    friendName: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Montserrat_600SemiBold',
        marginBottom: 2,
    },
    friendBio: {
        color: GRAY,
        fontSize: 13,
        fontFamily: 'Montserrat_500Medium',
    },
    emptyFriendsContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 30,
    },
    emptyFriendsText: {
        color: '#fff',
        fontSize: 18,
        fontFamily: 'Montserrat_700Bold',
        marginTop: 20,
    },
    emptyFriendsSubtext: {
        color: GRAY,
        fontSize: 14,
        textAlign: 'center',
        marginTop: 8,
        fontFamily: 'Montserrat_500Medium',
        lineHeight: 20,
    },
    exploreFriendsButton: {
        backgroundColor: NEON,
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 28,
        borderRadius: 30,
        marginTop: 32,
    },
    exploreFriendsText: {
        color: '#000',
        fontSize: 15,
        fontFamily: 'Montserrat_700Bold',
    },
    actionButtons: {
        flexDirection: 'row',
        marginTop: 24,
        gap: 12,
        width: '100%',
        paddingHorizontal: 20,
    },
    primaryBtn: {
        flex: 1,
        backgroundColor: NEON,
        paddingVertical: 10,
        paddingHorizontal: 5,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    primaryBtnText: {
        color: '#000',
        fontSize: 15,
        fontFamily: 'Montserrat_700Bold',
    },
    secondaryBtn: {
        flex: 1,
        backgroundColor: '#050505',
        paddingVertical: 10,
        paddingHorizontal: 5,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#333',
    },
    secondaryBtnText: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_600SemiBold',
    },
    // Avatar Picker Modal Styles
    avatarPickerContent: {
        backgroundColor: CARD_BG,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingBottom: 40,
        borderTopWidth: 1,
        borderColor: '#333',
    },
    avatarPickerSubtitle: {
        color: GRAY,
        fontSize: 15,
        textAlign: 'center',
        marginBottom: 32,
        fontFamily: 'Montserrat_500Medium',
    },
    avatarOptionsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        gap: 20,
        marginBottom: 32,
    },
    avatarOption: {
        alignItems: 'center',
    },
    avatarOptionRing: {
        width: 88,
        height: 88,
        borderRadius: 44,
        borderWidth: 2,
        borderColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#050505',
    },
    avatarOptionSelected: {
        borderColor: NEON,
    },
    refreshAvatarsButton: {
        backgroundColor: '#1A1A1A',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        paddingHorizontal: 24,
        borderRadius: 20,
        marginTop: 8,
        borderWidth: 1,
        borderColor: '#333',
    },
    refreshAvatarsText: {
        color: '#fff',
        fontSize: 15,
        fontFamily: 'Montserrat_600SemiBold',
    },
    savingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
    },
    savingText: {
        color: '#fff',
        fontSize: 15,
        marginTop: 16,
        fontFamily: 'Montserrat_600SemiBold',
    },

    // Achievements Modal Styles
    achievementsModalContent: {
        backgroundColor: CARD_BG,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 10,
        height: '85%',
        borderTopWidth: 1,
        borderColor: '#333',
    },
    achModalSubtitle: {
        color: GRAY,
        fontSize: 13,
        marginTop: 4,
        fontFamily: 'Montserrat_500Medium',
    },
    achievementsList: {
        flex: 1,
        marginTop: 20,
    },
    achievementModalItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#050505',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#1A1A1A',
    },
    achievementModalItemLocked: {
        opacity: 0.5,
        backgroundColor: '#050505',
        borderColor: '#111',
    },
    achModalCircle: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#1A1A1A',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
        borderWidth: 1,
        borderColor: '#222',
    },
    achModalCircleEarned: {
        backgroundColor: 'rgba(201, 226, 101, 0.1)',
        borderWidth: 1,
        borderColor: NEON,
    },
    achModalInfo: {
        flex: 1,
        marginRight: 12,
    },
    achModalName: {
        color: '#fff',
        fontSize: 16,
        fontFamily: 'Montserrat_700Bold',
        marginBottom: 4,
    },
    achModalNameLocked: {
        color: '#888',
    },
    achModalDesc: {
        color: GRAY,
        fontSize: 12,
        lineHeight: 16,
        fontFamily: 'Montserrat_500Medium',
    },
    achModalDescLocked: {
        color: '#555',
    },
    achModalDate: {
        color: NEON,
        fontSize: 11,
        marginTop: 6,
        fontFamily: 'Montserrat_600SemiBold',
    },
    emptyAchievements: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
    },
    emptyAchievementsText: {
        color: GRAY,
        fontSize: 15,
        marginTop: 20,
        fontFamily: 'Montserrat_600SemiBold',
    },
});

export default profileStyles;
